title: Rechtsanwalt Albrecht

headline: Kanzlei Dr.&nbsp;Albrecht
description: Dr. Gerald Albrecht - Ihr Rechtsanwalt und Verteidiger in Strafsachen<br/>
 im Herzen Wiens

bg-header: bg-dr.albrecht-office.jpg
bg-footer: bg-footer.jpg
logo: logo10.svg

nav:
- name: Die Kanzlei
  url: '#about-section'
- name: Kontakt
  url: '#contact-section'
- name: Presse
  url: '#press-section'

copyright: Copyright 2017

footernav:
- name: IMPRESSUM
  link: /impressum.html
- name: DATENSCHUTZ
  link: /datenschutz.html