title: Kanzlei Dr.&nbsp;Albrecht
email: Kanzlei-Albrecht@gmx.at
phone: 0043 1 7136302
address: Untere Viaduktgasse 10, 1030 Wien
office-hours: Mo-Fr 9:00-17:00 Uhr
date-aggreement: Termin nach Vereinbarung 
map: https://www.google.at/maps/place/Mr.+Dr.+Gerald+Albrecht/@48.2064703,16.3847183,17z/data=!3m1!4b1!4m5!3m4!1s0x476d077313e34d13:0x4f27537b29d3c433!8m2!3d48.2064703!4d16.386907
description: Dr. Albrecht - Ihr Verteidiger in Strafsachen im Herzen Wiens
# bg-img: Geri-bg.png
bg-img: bg-dr.albrecht.jpg
logo: logo.svg

menu:
- {name: Die Kanzlei, url: '#about'}
- {name: Kontakt, url: '#contact'}
- {name: Presse, url: '#press'}
# - {name: Klienten, url: '#'}


diekanzlei: <p><strong>Ich vertrete Sie </strong>in den Bereichen Miet- und Wohnrecht, Ehe- und Familienrecht,
 Strafrecht, Handels- und Unternehmensrecht, Verkehrsrecht und bei Unfallschäden.<br/><br/>
 <strong>Mein Schwerpunkt </strong>liegt dabei sowohl in der ausführlichen Beratung wie auch in
 der durchsetzungsstarken Vertretung vor Gericht.<br/><br/>
 <strong>Mein oberstes Prinzip </strong>dabei ist, Ihnen in allen
 notwendigen Schritten zu Seite zu stehen und mit meiner langjährigen Erfahrung und viel
 Einfühlungsvermögen auf Ihren individuellen Fall einzugehen. Ein professionelles Vorgehen steht
 dabei immer an erster Stelle, vor allen Dingen darf aber die Menschlichkeit bei mir nicht zu kurz
 kommen. <br/><br/>
 <strong>Bei Fragen wie auch zur Terminvereinbarung </strong>für das Erstgespräch stehe ich Ihnen mit
 meinem Team zu Verfügung.</p>

pr-email: Ruth.Albrecht@gmx.at

press:
- {text: 'Profil, 11.02.2013', url: 'http://www.profil.at/home/entziehungsberechtigungen-diplomatische-affaere-obsorgestreit-352238'}
- {text: 'Kronen Zeitung, 29.01.2006', url: 'http://www.krone.at/oesterreich/die-beichte-des-saliera-diebs-die-grosse-beichte-story-41817'}
- {text: 'Profil, 28.01.2006', url: 'http://www.profil.at/home/saliera-sicherheitsrisiko-seipel-131779'}

copyright: Copyright 2017
